
/* Generated by glcurrent.pl */
#include "glcontext.h"

#define CONVERT_us(a) ((GLfloat) (a))
#define CONVERT_i(a) ((GLfloat) (a))
#define CONVERT_b(a) ((GLfloat) (a))
#define CONVERT_s(a) ((GLfloat) (a))
#define CONVERT_d(a) ((GLfloat) (a))
#define CONVERT_l(a) ((GLfloat) (a))
#define CONVERT_f(a) ((GLfloat) (a))
#define CONVERT_ui(a) ((GLfloat) (a))
#define CONVERT_ub(a) ((GLfloat) (a))
#define CONVERT_RESCALE_us(a) (((GLfloat) (a)) / GL_MAXUSHORT)

#define CONVERT_RESCALE_i(a) (((GLfloat) (a)) / GL_MAXINT)

#define CONVERT_RESCALE_b(a) (((GLfloat) (a)) / GL_MAXBYTE)

#define CONVERT_RESCALE_s(a) (((GLfloat) (a)) / GL_MAXSHORT)

#define CONVERT_RESCALE_ui(a) (((GLfloat) (a)) / GL_MAXUINT)

#define CONVERT_RESCALE_ub(a) (((GLfloat) (a)) / GL_MAXUBYTE)

void GLSTATE_DECL __glstate_Indexub(GLubyte v0)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->index = CONVERT_ub (v0);
}

void GLSTATE_DECL __glstate_Indexs(GLshort v0)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->index = CONVERT_s (v0);
}

void GLSTATE_DECL __glstate_Indexi(GLint v0)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->index = CONVERT_i (v0);
}

void GLSTATE_DECL __glstate_Indexf(GLfloat v0)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->index =  (v0);
}

void GLSTATE_DECL __glstate_Indexd(GLdouble v0)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->index = CONVERT_d (v0);
}

void GLSTATE_DECL __glstate_TexCoord1s(GLshort v0)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_s (v0);
  c->texcoord.t = 0;
  c->texcoord.p = 0;
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord2s(GLshort v0, GLshort v1)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_s (v0);
  c->texcoord.t = CONVERT_s (v1);
  c->texcoord.p = 0;
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord3s(GLshort v0, GLshort v1, GLshort v2)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_s (v0);
  c->texcoord.t = CONVERT_s (v1);
  c->texcoord.p = CONVERT_s (v2);
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord4s(GLshort v0, GLshort v1, GLshort v2, GLshort v3)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_s (v0);
  c->texcoord.t = CONVERT_s (v1);
  c->texcoord.p = CONVERT_s (v2);
  c->texcoord.q = CONVERT_s (v3);
}

void GLSTATE_DECL __glstate_TexCoord1i(GLint v0)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_i (v0);
  c->texcoord.t = 0;
  c->texcoord.p = 0;
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord2i(GLint v0, GLint v1)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_i (v0);
  c->texcoord.t = CONVERT_i (v1);
  c->texcoord.p = 0;
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord3i(GLint v0, GLint v1, GLint v2)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_i (v0);
  c->texcoord.t = CONVERT_i (v1);
  c->texcoord.p = CONVERT_i (v2);
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord4i(GLint v0, GLint v1, GLint v2, GLint v3)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_i (v0);
  c->texcoord.t = CONVERT_i (v1);
  c->texcoord.p = CONVERT_i (v2);
  c->texcoord.q = CONVERT_i (v3);
}

void GLSTATE_DECL __glstate_TexCoord1f(GLfloat v0)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s =  (v0);
  c->texcoord.t = 0;
  c->texcoord.p = 0;
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord2f(GLfloat v0, GLfloat v1)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s =  (v0);
  c->texcoord.t =  (v1);
  c->texcoord.p = 0;
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord3f(GLfloat v0, GLfloat v1, GLfloat v2)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s =  (v0);
  c->texcoord.t =  (v1);
  c->texcoord.p =  (v2);
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord4f(GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s =  (v0);
  c->texcoord.t =  (v1);
  c->texcoord.p =  (v2);
  c->texcoord.q =  (v3);
}

void GLSTATE_DECL __glstate_TexCoord1d(GLdouble v0)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_d (v0);
  c->texcoord.t = 0;
  c->texcoord.p = 0;
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord2d(GLdouble v0, GLdouble v1)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_d (v0);
  c->texcoord.t = CONVERT_d (v1);
  c->texcoord.p = 0;
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord3d(GLdouble v0, GLdouble v1, GLdouble v2)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_d (v0);
  c->texcoord.t = CONVERT_d (v1);
  c->texcoord.p = CONVERT_d (v2);
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord4d(GLdouble v0, GLdouble v1, GLdouble v2, GLdouble v3)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_d (v0);
  c->texcoord.t = CONVERT_d (v1);
  c->texcoord.p = CONVERT_d (v2);
  c->texcoord.q = CONVERT_d (v3);
}

void GLSTATE_DECL __glstate_Normal3b(GLbyte v0, GLbyte v1, GLbyte v2)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->normal.x = CONVERT_RESCALE_b (v0);
  c->normal.y = CONVERT_RESCALE_b (v1);
  c->normal.z = CONVERT_RESCALE_b (v2);
}

void GLSTATE_DECL __glstate_Normal3s(GLshort v0, GLshort v1, GLshort v2)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->normal.x = CONVERT_RESCALE_s (v0);
  c->normal.y = CONVERT_RESCALE_s (v1);
  c->normal.z = CONVERT_RESCALE_s (v2);
}

void GLSTATE_DECL __glstate_Normal3i(GLint v0, GLint v1, GLint v2)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->normal.x = CONVERT_RESCALE_i (v0);
  c->normal.y = CONVERT_RESCALE_i (v1);
  c->normal.z = CONVERT_RESCALE_i (v2);
}

void GLSTATE_DECL __glstate_Normal3f(GLfloat v0, GLfloat v1, GLfloat v2)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->normal.x =  (v0);
  c->normal.y =  (v1);
  c->normal.z =  (v2);
}

void GLSTATE_DECL __glstate_Normal3d(GLdouble v0, GLdouble v1, GLdouble v2)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->normal.x = CONVERT_d (v0);
  c->normal.y = CONVERT_d (v1);
  c->normal.z = CONVERT_d (v2);
}

void GLSTATE_DECL __glstate_EdgeFlag(GLboolean v0)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->edgeflag =  (v0);
}

void GLSTATE_DECL __glstate_Color3b(GLbyte v0, GLbyte v1, GLbyte v2)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_b (v0);
  c->color.g = CONVERT_RESCALE_b (v1);
  c->color.b = CONVERT_RESCALE_b (v2);
  c->color.a = 1;
}

void GLSTATE_DECL __glstate_Color4b(GLbyte v0, GLbyte v1, GLbyte v2, GLbyte v3)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_b (v0);
  c->color.g = CONVERT_RESCALE_b (v1);
  c->color.b = CONVERT_RESCALE_b (v2);
  c->color.a = CONVERT_RESCALE_b (v3);
}

void GLSTATE_DECL __glstate_Color3ub(GLubyte v0, GLubyte v1, GLubyte v2)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_ub (v0);
  c->color.g = CONVERT_RESCALE_ub (v1);
  c->color.b = CONVERT_RESCALE_ub (v2);
  c->color.a = 1;
}

void GLSTATE_DECL __glstate_Color4ub(GLubyte v0, GLubyte v1, GLubyte v2, GLubyte v3)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_ub (v0);
  c->color.g = CONVERT_RESCALE_ub (v1);
  c->color.b = CONVERT_RESCALE_ub (v2);
  c->color.a = CONVERT_RESCALE_ub (v3);
}

void GLSTATE_DECL __glstate_Color3s(GLshort v0, GLshort v1, GLshort v2)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_s (v0);
  c->color.g = CONVERT_RESCALE_s (v1);
  c->color.b = CONVERT_RESCALE_s (v2);
  c->color.a = 1;
}

void GLSTATE_DECL __glstate_Color4s(GLshort v0, GLshort v1, GLshort v2, GLshort v3)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_s (v0);
  c->color.g = CONVERT_RESCALE_s (v1);
  c->color.b = CONVERT_RESCALE_s (v2);
  c->color.a = CONVERT_RESCALE_s (v3);
}

void GLSTATE_DECL __glstate_Color3us(GLushort v0, GLushort v1, GLushort v2)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_us (v0);
  c->color.g = CONVERT_RESCALE_us (v1);
  c->color.b = CONVERT_RESCALE_us (v2);
  c->color.a = 1;
}

void GLSTATE_DECL __glstate_Color4us(GLushort v0, GLushort v1, GLushort v2, GLushort v3)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_us (v0);
  c->color.g = CONVERT_RESCALE_us (v1);
  c->color.b = CONVERT_RESCALE_us (v2);
  c->color.a = CONVERT_RESCALE_us (v3);
}

void GLSTATE_DECL __glstate_Color3i(GLint v0, GLint v1, GLint v2)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_i (v0);
  c->color.g = CONVERT_RESCALE_i (v1);
  c->color.b = CONVERT_RESCALE_i (v2);
  c->color.a = 1;
}

void GLSTATE_DECL __glstate_Color4i(GLint v0, GLint v1, GLint v2, GLint v3)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_i (v0);
  c->color.g = CONVERT_RESCALE_i (v1);
  c->color.b = CONVERT_RESCALE_i (v2);
  c->color.a = CONVERT_RESCALE_i (v3);
}

void GLSTATE_DECL __glstate_Color3ui(GLuint v0, GLuint v1, GLuint v2)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_ui (v0);
  c->color.g = CONVERT_RESCALE_ui (v1);
  c->color.b = CONVERT_RESCALE_ui (v2);
  c->color.a = 1;
}

void GLSTATE_DECL __glstate_Color4ui(GLuint v0, GLuint v1, GLuint v2, GLuint v3)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_ui (v0);
  c->color.g = CONVERT_RESCALE_ui (v1);
  c->color.b = CONVERT_RESCALE_ui (v2);
  c->color.a = CONVERT_RESCALE_ui (v3);
}

void GLSTATE_DECL __glstate_Color3f(GLfloat v0, GLfloat v1, GLfloat v2)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r =  (v0);
  c->color.g =  (v1);
  c->color.b =  (v2);
  c->color.a = 1;
}

void GLSTATE_DECL __glstate_Color4f(GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r =  (v0);
  c->color.g =  (v1);
  c->color.b =  (v2);
  c->color.a =  (v3);
}

void GLSTATE_DECL __glstate_Color3d(GLdouble v0, GLdouble v1, GLdouble v2)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_d (v0);
  c->color.g = CONVERT_d (v1);
  c->color.b = CONVERT_d (v2);
  c->color.a = 1;
}

void GLSTATE_DECL __glstate_Color4d(GLdouble v0, GLdouble v1, GLdouble v2, GLdouble v3)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_d (v0);
  c->color.g = CONVERT_d (v1);
  c->color.b = CONVERT_d (v2);
  c->color.a = CONVERT_d (v3);
}

void GLSTATE_DECL __glstate_Indexubv(const GLubyte *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->index = CONVERT_ub (v[0]);
}

void GLSTATE_DECL __glstate_Indexsv(const GLshort *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->index = CONVERT_s (v[0]);
}

void GLSTATE_DECL __glstate_Indexiv(const GLint *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->index = CONVERT_i (v[0]);
}

void GLSTATE_DECL __glstate_Indexfv(const GLfloat *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->index =  (v[0]);
}

void GLSTATE_DECL __glstate_Indexdv(const GLdouble *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->index = CONVERT_d (v[0]);
}

void GLSTATE_DECL __glstate_TexCoord1sv(const GLshort *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_s (v[0]);
  c->texcoord.t = 0;
  c->texcoord.p = 0;
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord2sv(const GLshort *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_s (v[0]);
  c->texcoord.t = CONVERT_s (v[1]);
  c->texcoord.p = 0;
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord3sv(const GLshort *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_s (v[0]);
  c->texcoord.t = CONVERT_s (v[1]);
  c->texcoord.p = CONVERT_s (v[2]);
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord4sv(const GLshort *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_s (v[0]);
  c->texcoord.t = CONVERT_s (v[1]);
  c->texcoord.p = CONVERT_s (v[2]);
  c->texcoord.q = CONVERT_s (v[3]);
}

void GLSTATE_DECL __glstate_TexCoord1iv(const GLint *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_i (v[0]);
  c->texcoord.t = 0;
  c->texcoord.p = 0;
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord2iv(const GLint *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_i (v[0]);
  c->texcoord.t = CONVERT_i (v[1]);
  c->texcoord.p = 0;
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord3iv(const GLint *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_i (v[0]);
  c->texcoord.t = CONVERT_i (v[1]);
  c->texcoord.p = CONVERT_i (v[2]);
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord4iv(const GLint *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_i (v[0]);
  c->texcoord.t = CONVERT_i (v[1]);
  c->texcoord.p = CONVERT_i (v[2]);
  c->texcoord.q = CONVERT_i (v[3]);
}

void GLSTATE_DECL __glstate_TexCoord1fv(const GLfloat *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s =  (v[0]);
  c->texcoord.t = 0;
  c->texcoord.p = 0;
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord2fv(const GLfloat *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s =  (v[0]);
  c->texcoord.t =  (v[1]);
  c->texcoord.p = 0;
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord3fv(const GLfloat *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s =  (v[0]);
  c->texcoord.t =  (v[1]);
  c->texcoord.p =  (v[2]);
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord4fv(const GLfloat *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s =  (v[0]);
  c->texcoord.t =  (v[1]);
  c->texcoord.p =  (v[2]);
  c->texcoord.q =  (v[3]);
}

void GLSTATE_DECL __glstate_TexCoord1dv(const GLdouble *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_d (v[0]);
  c->texcoord.t = 0;
  c->texcoord.p = 0;
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord2dv(const GLdouble *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_d (v[0]);
  c->texcoord.t = CONVERT_d (v[1]);
  c->texcoord.p = 0;
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord3dv(const GLdouble *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_d (v[0]);
  c->texcoord.t = CONVERT_d (v[1]);
  c->texcoord.p = CONVERT_d (v[2]);
  c->texcoord.q = 1;
}

void GLSTATE_DECL __glstate_TexCoord4dv(const GLdouble *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->texcoord.s = CONVERT_d (v[0]);
  c->texcoord.t = CONVERT_d (v[1]);
  c->texcoord.p = CONVERT_d (v[2]);
  c->texcoord.q = CONVERT_d (v[3]);
}

void GLSTATE_DECL __glstate_Normal3bv(const GLbyte *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->normal.x = CONVERT_RESCALE_b (v[0]);
  c->normal.y = CONVERT_RESCALE_b (v[1]);
  c->normal.z = CONVERT_RESCALE_b (v[2]);
}

void GLSTATE_DECL __glstate_Normal3sv(const GLshort *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->normal.x = CONVERT_RESCALE_s (v[0]);
  c->normal.y = CONVERT_RESCALE_s (v[1]);
  c->normal.z = CONVERT_RESCALE_s (v[2]);
}

void GLSTATE_DECL __glstate_Normal3iv(const GLint *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->normal.x = CONVERT_RESCALE_i (v[0]);
  c->normal.y = CONVERT_RESCALE_i (v[1]);
  c->normal.z = CONVERT_RESCALE_i (v[2]);
}

void GLSTATE_DECL __glstate_Normal3fv(const GLfloat *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->normal.x =  (v[0]);
  c->normal.y =  (v[1]);
  c->normal.z =  (v[2]);
}

void GLSTATE_DECL __glstate_Normal3dv(const GLdouble *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->normal.x = CONVERT_d (v[0]);
  c->normal.y = CONVERT_d (v[1]);
  c->normal.z = CONVERT_d (v[2]);
}

void GLSTATE_DECL __glstate_EdgeFlagv(const GLboolean *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->edgeflag =  (v[0]);
}

void GLSTATE_DECL __glstate_Color3bv(const GLbyte *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_b (v[0]);
  c->color.g = CONVERT_RESCALE_b (v[1]);
  c->color.b = CONVERT_RESCALE_b (v[2]);
  c->color.a = 1;
}

void GLSTATE_DECL __glstate_Color4bv(const GLbyte *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_b (v[0]);
  c->color.g = CONVERT_RESCALE_b (v[1]);
  c->color.b = CONVERT_RESCALE_b (v[2]);
  c->color.a = CONVERT_RESCALE_b (v[3]);
}

void GLSTATE_DECL __glstate_Color3ubv(const GLubyte *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_ub (v[0]);
  c->color.g = CONVERT_RESCALE_ub (v[1]);
  c->color.b = CONVERT_RESCALE_ub (v[2]);
  c->color.a = 1;
}

void GLSTATE_DECL __glstate_Color4ubv(const GLubyte *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_ub (v[0]);
  c->color.g = CONVERT_RESCALE_ub (v[1]);
  c->color.b = CONVERT_RESCALE_ub (v[2]);
  c->color.a = CONVERT_RESCALE_ub (v[3]);
}

void GLSTATE_DECL __glstate_Color3sv(const GLshort *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_s (v[0]);
  c->color.g = CONVERT_RESCALE_s (v[1]);
  c->color.b = CONVERT_RESCALE_s (v[2]);
  c->color.a = 1;
}

void GLSTATE_DECL __glstate_Color4sv(const GLshort *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_s (v[0]);
  c->color.g = CONVERT_RESCALE_s (v[1]);
  c->color.b = CONVERT_RESCALE_s (v[2]);
  c->color.a = CONVERT_RESCALE_s (v[3]);
}

void GLSTATE_DECL __glstate_Color3usv(const GLushort *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_us (v[0]);
  c->color.g = CONVERT_RESCALE_us (v[1]);
  c->color.b = CONVERT_RESCALE_us (v[2]);
  c->color.a = 1;
}

void GLSTATE_DECL __glstate_Color4usv(const GLushort *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_us (v[0]);
  c->color.g = CONVERT_RESCALE_us (v[1]);
  c->color.b = CONVERT_RESCALE_us (v[2]);
  c->color.a = CONVERT_RESCALE_us (v[3]);
}

void GLSTATE_DECL __glstate_Color3iv(const GLint *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_i (v[0]);
  c->color.g = CONVERT_RESCALE_i (v[1]);
  c->color.b = CONVERT_RESCALE_i (v[2]);
  c->color.a = 1;
}

void GLSTATE_DECL __glstate_Color4iv(const GLint *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_i (v[0]);
  c->color.g = CONVERT_RESCALE_i (v[1]);
  c->color.b = CONVERT_RESCALE_i (v[2]);
  c->color.a = CONVERT_RESCALE_i (v[3]);
}

void GLSTATE_DECL __glstate_Color3uiv(const GLuint *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_ui (v[0]);
  c->color.g = CONVERT_RESCALE_ui (v[1]);
  c->color.b = CONVERT_RESCALE_ui (v[2]);
  c->color.a = 1;
}

void GLSTATE_DECL __glstate_Color4uiv(const GLuint *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_RESCALE_ui (v[0]);
  c->color.g = CONVERT_RESCALE_ui (v[1]);
  c->color.b = CONVERT_RESCALE_ui (v[2]);
  c->color.a = CONVERT_RESCALE_ui (v[3]);
}

void GLSTATE_DECL __glstate_Color3fv(const GLfloat *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r =  (v[0]);
  c->color.g =  (v[1]);
  c->color.b =  (v[2]);
  c->color.a = 1;
}

void GLSTATE_DECL __glstate_Color4fv(const GLfloat *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r =  (v[0]);
  c->color.g =  (v[1]);
  c->color.b =  (v[2]);
  c->color.a =  (v[3]);
}

void GLSTATE_DECL __glstate_Color3dv(const GLdouble *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_d (v[0]);
  c->color.g = CONVERT_d (v[1]);
  c->color.b = CONVERT_d (v[2]);
  c->color.a = 1;
}

void GLSTATE_DECL __glstate_Color4dv(const GLdouble *v)
{
  GLcontext *g = GetCurrentContext();
  GLcurrentstate *c = &(g->current);
  c->color.r = CONVERT_d (v[0]);
  c->color.g = CONVERT_d (v[1]);
  c->color.b = CONVERT_d (v[2]);
  c->color.a = CONVERT_d (v[3]);
}

