
/* Generated by exports.pl */
#include "funcptrs.h"
#ifdef WIN32
#define NAKED __declspec(naked)
#else
#define NAKED
#endif

#ifdef __cplusplus
extern "C" {
#endif

NAKED glAccum() {
	__asm jmp [__glim_Accum]
}

NAKED glAlphaFunc() {
	__asm jmp [__glim_AlphaFunc]
}

NAKED glAreTexturesResident() {
	__asm jmp [__glim_AreTexturesResident]
}

NAKED glArrayElement() {
	__asm jmp [__glim_ArrayElement]
}

NAKED glBegin() {
	__asm jmp [__glim_Begin]
}

NAKED glBindTexture() {
	__asm jmp [__glim_BindTexture]
}

NAKED glBitmap() {
	__asm jmp [__glim_Bitmap]
}

NAKED glBlendFunc() {
	__asm jmp [__glim_BlendFunc]
}

NAKED glCallList() {
	__asm jmp [__glim_CallList]
}

NAKED glCallLists() {
	__asm jmp [__glim_CallLists]
}

NAKED glClear() {
	__asm jmp [__glim_Clear]
}

NAKED glClearAccum() {
	__asm jmp [__glim_ClearAccum]
}

NAKED glClearColor() {
	__asm jmp [__glim_ClearColor]
}

NAKED glClearDepth() {
	__asm jmp [__glim_ClearDepth]
}

NAKED glClearIndex() {
	__asm jmp [__glim_ClearIndex]
}

NAKED glClearStencil() {
	__asm jmp [__glim_ClearStencil]
}

NAKED glClipPlane() {
	__asm jmp [__glim_ClipPlane]
}

NAKED glColor3b() {
	__asm jmp [__glim_Color3b]
}

NAKED glColor3bv() {
	__asm jmp [__glim_Color3bv]
}

NAKED glColor3d() {
	__asm jmp [__glim_Color3d]
}

NAKED glColor3dv() {
	__asm jmp [__glim_Color3dv]
}

NAKED glColor3f() {
	__asm jmp [__glim_Color3f]
}

NAKED glColor3fv() {
	__asm jmp [__glim_Color3fv]
}

NAKED glColor3i() {
	__asm jmp [__glim_Color3i]
}

NAKED glColor3iv() {
	__asm jmp [__glim_Color3iv]
}

NAKED glColor3s() {
	__asm jmp [__glim_Color3s]
}

NAKED glColor3sv() {
	__asm jmp [__glim_Color3sv]
}

NAKED glColor3ub() {
	__asm jmp [__glim_Color3ub]
}

NAKED glColor3ubv() {
	__asm jmp [__glim_Color3ubv]
}

NAKED glColor3ui() {
	__asm jmp [__glim_Color3ui]
}

NAKED glColor3uiv() {
	__asm jmp [__glim_Color3uiv]
}

NAKED glColor3us() {
	__asm jmp [__glim_Color3us]
}

NAKED glColor3usv() {
	__asm jmp [__glim_Color3usv]
}

NAKED glColor4b() {
	__asm jmp [__glim_Color4b]
}

NAKED glColor4bv() {
	__asm jmp [__glim_Color4bv]
}

NAKED glColor4d() {
	__asm jmp [__glim_Color4d]
}

NAKED glColor4dv() {
	__asm jmp [__glim_Color4dv]
}

NAKED glColor4f() {
	__asm jmp [__glim_Color4f]
}

NAKED glColor4fv() {
	__asm jmp [__glim_Color4fv]
}

NAKED glColor4i() {
	__asm jmp [__glim_Color4i]
}

NAKED glColor4iv() {
	__asm jmp [__glim_Color4iv]
}

NAKED glColor4s() {
	__asm jmp [__glim_Color4s]
}

NAKED glColor4sv() {
	__asm jmp [__glim_Color4sv]
}

NAKED glColor4ub() {
	__asm jmp [__glim_Color4ub]
}

NAKED glColor4ubv() {
	__asm jmp [__glim_Color4ubv]
}

NAKED glColor4ui() {
	__asm jmp [__glim_Color4ui]
}

NAKED glColor4uiv() {
	__asm jmp [__glim_Color4uiv]
}

NAKED glColor4us() {
	__asm jmp [__glim_Color4us]
}

NAKED glColor4usv() {
	__asm jmp [__glim_Color4usv]
}

NAKED glColorMask() {
	__asm jmp [__glim_ColorMask]
}

NAKED glColorMaterial() {
	__asm jmp [__glim_ColorMaterial]
}

NAKED glColorPointer() {
	__asm jmp [__glim_ColorPointer]
}

NAKED glCopyPixels() {
	__asm jmp [__glim_CopyPixels]
}

NAKED glCopyTexImage1D() {
	__asm jmp [__glim_CopyTexImage1D]
}

NAKED glCopyTexImage2D() {
	__asm jmp [__glim_CopyTexImage2D]
}

NAKED glCopyTexSubImage1D() {
	__asm jmp [__glim_CopyTexSubImage1D]
}

NAKED glCopyTexSubImage2D() {
	__asm jmp [__glim_CopyTexSubImage2D]
}

NAKED glCullFace() {
	__asm jmp [__glim_CullFace]
}

NAKED glDeleteLists() {
	__asm jmp [__glim_DeleteLists]
}

NAKED glDeleteTextures() {
	__asm jmp [__glim_DeleteTextures]
}

NAKED glDepthFunc() {
	__asm jmp [__glim_DepthFunc]
}

NAKED glDepthMask() {
	__asm jmp [__glim_DepthMask]
}

NAKED glDepthRange() {
	__asm jmp [__glim_DepthRange]
}

NAKED glDisable() {
	__asm jmp [__glim_Disable]
}

NAKED glDisableClientState() {
	__asm jmp [__glim_DisableClientState]
}

NAKED glDrawArrays() {
	__asm jmp [__glim_DrawArrays]
}

NAKED glDrawBuffer() {
	__asm jmp [__glim_DrawBuffer]
}

NAKED glDrawElements() {
	__asm jmp [__glim_DrawElements]
}

NAKED glDrawPixels() {
	__asm jmp [__glim_DrawPixels]
}

NAKED glEdgeFlag() {
	__asm jmp [__glim_EdgeFlag]
}

NAKED glEdgeFlagPointer() {
	__asm jmp [__glim_EdgeFlagPointer]
}

NAKED glEdgeFlagv() {
	__asm jmp [__glim_EdgeFlagv]
}

NAKED glEnable() {
	__asm jmp [__glim_Enable]
}

NAKED glEnableClientState() {
	__asm jmp [__glim_EnableClientState]
}

NAKED glEnd() {
	__asm jmp [__glim_End]
}

NAKED glEndList() {
	__asm jmp [__glim_EndList]
}

NAKED glEvalCoord1d() {
	__asm jmp [__glim_EvalCoord1d]
}

NAKED glEvalCoord1dv() {
	__asm jmp [__glim_EvalCoord1dv]
}

NAKED glEvalCoord1f() {
	__asm jmp [__glim_EvalCoord1f]
}

NAKED glEvalCoord1fv() {
	__asm jmp [__glim_EvalCoord1fv]
}

NAKED glEvalCoord2d() {
	__asm jmp [__glim_EvalCoord2d]
}

NAKED glEvalCoord2dv() {
	__asm jmp [__glim_EvalCoord2dv]
}

NAKED glEvalCoord2f() {
	__asm jmp [__glim_EvalCoord2f]
}

NAKED glEvalCoord2fv() {
	__asm jmp [__glim_EvalCoord2fv]
}

NAKED glEvalMesh1() {
	__asm jmp [__glim_EvalMesh1]
}

NAKED glEvalMesh2() {
	__asm jmp [__glim_EvalMesh2]
}

NAKED glEvalPoint1() {
	__asm jmp [__glim_EvalPoint1]
}

NAKED glEvalPoint2() {
	__asm jmp [__glim_EvalPoint2]
}

NAKED glFeedbackBuffer() {
	__asm jmp [__glim_FeedbackBuffer]
}

NAKED glFinish() {
	__asm jmp [__glim_Finish]
}

NAKED glFlush() {
	__asm jmp [__glim_Flush]
}

NAKED glFogf() {
	__asm jmp [__glim_Fogf]
}

NAKED glFogfv() {
	__asm jmp [__glim_Fogfv]
}

NAKED glFogi() {
	__asm jmp [__glim_Fogi]
}

NAKED glFogiv() {
	__asm jmp [__glim_Fogiv]
}

NAKED glFrontFace() {
	__asm jmp [__glim_FrontFace]
}

NAKED glFrustum() {
	__asm jmp [__glim_Frustum]
}

NAKED glGenLists() {
	__asm jmp [__glim_GenLists]
}

NAKED glGenTextures() {
	__asm jmp [__glim_GenTextures]
}

NAKED glGetBooleanv() {
	__asm jmp [__glim_GetBooleanv]
}

NAKED glGetClipPlane() {
	__asm jmp [__glim_GetClipPlane]
}

NAKED glGetDoublev() {
	__asm jmp [__glim_GetDoublev]
}

NAKED glGetError() {
	__asm jmp [__glim_GetError]
}

NAKED glGetFloatv() {
	__asm jmp [__glim_GetFloatv]
}

NAKED glGetIntegerv() {
	__asm jmp [__glim_GetIntegerv]
}

NAKED glGetLightfv() {
	__asm jmp [__glim_GetLightfv]
}

NAKED glGetLightiv() {
	__asm jmp [__glim_GetLightiv]
}

NAKED glGetMapdv() {
	__asm jmp [__glim_GetMapdv]
}

NAKED glGetMapfv() {
	__asm jmp [__glim_GetMapfv]
}

NAKED glGetMapiv() {
	__asm jmp [__glim_GetMapiv]
}

NAKED glGetMaterialfv() {
	__asm jmp [__glim_GetMaterialfv]
}

NAKED glGetMaterialiv() {
	__asm jmp [__glim_GetMaterialiv]
}

NAKED glGetPixelMapfv() {
	__asm jmp [__glim_GetPixelMapfv]
}

NAKED glGetPixelMapuiv() {
	__asm jmp [__glim_GetPixelMapuiv]
}

NAKED glGetPixelMapusv() {
	__asm jmp [__glim_GetPixelMapusv]
}

NAKED glGetPointerv() {
	__asm jmp [__glim_GetPointerv]
}

NAKED glGetPolygonStipple () {
	__asm jmp [__glim_GetPolygonStipple ]
}

NAKED glGetString() {
	__asm jmp [__glim_GetString]
}

NAKED glGetTexEnvfv() {
	__asm jmp [__glim_GetTexEnvfv]
}

NAKED glGetTexEnviv() {
	__asm jmp [__glim_GetTexEnviv]
}

NAKED glGetTexGendv() {
	__asm jmp [__glim_GetTexGendv]
}

NAKED glGetTexGenfv() {
	__asm jmp [__glim_GetTexGenfv]
}

NAKED glGetTexGeniv() {
	__asm jmp [__glim_GetTexGeniv]
}

NAKED glGetTexImage() {
	__asm jmp [__glim_GetTexImage]
}

NAKED glGetTexLevelParameterfv() {
	__asm jmp [__glim_GetTexLevelParameterfv]
}

NAKED glGetTexLevelParameteriv() {
	__asm jmp [__glim_GetTexLevelParameteriv]
}

NAKED glGetTexParameterfv() {
	__asm jmp [__glim_GetTexParameterfv]
}

NAKED glGetTexParameteriv() {
	__asm jmp [__glim_GetTexParameteriv]
}

NAKED glHint() {
	__asm jmp [__glim_Hint]
}

NAKED glIndexMask() {
	__asm jmp [__glim_IndexMask]
}

NAKED glIndexPointer() {
	__asm jmp [__glim_IndexPointer]
}

NAKED glIndexd() {
	__asm jmp [__glim_Indexd]
}

NAKED glIndexdv() {
	__asm jmp [__glim_Indexdv]
}

NAKED glIndexf() {
	__asm jmp [__glim_Indexf]
}

NAKED glIndexfv() {
	__asm jmp [__glim_Indexfv]
}

NAKED glIndexi() {
	__asm jmp [__glim_Indexi]
}

NAKED glIndexiv() {
	__asm jmp [__glim_Indexiv]
}

NAKED glIndexs() {
	__asm jmp [__glim_Indexs]
}

NAKED glIndexsv() {
	__asm jmp [__glim_Indexsv]
}

NAKED glIndexub() {
	__asm jmp [__glim_Indexub]
}

NAKED glIndexubv() {
	__asm jmp [__glim_Indexubv]
}

NAKED glInitNames() {
	__asm jmp [__glim_InitNames]
}

NAKED glInterleavedArrays() {
	__asm jmp [__glim_InterleavedArrays]
}

NAKED glIsEnabled() {
	__asm jmp [__glim_IsEnabled]
}

NAKED glIsList() {
	__asm jmp [__glim_IsList]
}

NAKED glIsTexture() {
	__asm jmp [__glim_IsTexture]
}

NAKED glLightModelf() {
	__asm jmp [__glim_LightModelf]
}

NAKED glLightModelfv() {
	__asm jmp [__glim_LightModelfv]
}

NAKED glLightModeli() {
	__asm jmp [__glim_LightModeli]
}

NAKED glLightModeliv() {
	__asm jmp [__glim_LightModeliv]
}

NAKED glLightf() {
	__asm jmp [__glim_Lightf]
}

NAKED glLightfv() {
	__asm jmp [__glim_Lightfv]
}

NAKED glLighti() {
	__asm jmp [__glim_Lighti]
}

NAKED glLightiv() {
	__asm jmp [__glim_Lightiv]
}

NAKED glLineStipple() {
	__asm jmp [__glim_LineStipple]
}

NAKED glLineWidth() {
	__asm jmp [__glim_LineWidth]
}

NAKED glListBase() {
	__asm jmp [__glim_ListBase]
}

NAKED glLoadIdentity() {
	__asm jmp [__glim_LoadIdentity]
}

NAKED glLoadMatrixd() {
	__asm jmp [__glim_LoadMatrixd]
}

NAKED glLoadMatrixf() {
	__asm jmp [__glim_LoadMatrixf]
}

NAKED glLoadName() {
	__asm jmp [__glim_LoadName]
}

NAKED glLogicOp() {
	__asm jmp [__glim_LogicOp]
}

NAKED glMap1d() {
	__asm jmp [__glim_Map1d]
}

NAKED glMap1f() {
	__asm jmp [__glim_Map1f]
}

NAKED glMap2d() {
	__asm jmp [__glim_Map2d]
}

NAKED glMap2f() {
	__asm jmp [__glim_Map2f]
}

NAKED glMapGrid1d() {
	__asm jmp [__glim_MapGrid1d]
}

NAKED glMapGrid1f() {
	__asm jmp [__glim_MapGrid1f]
}

NAKED glMapGrid2d() {
	__asm jmp [__glim_MapGrid2d]
}

NAKED glMapGrid2f() {
	__asm jmp [__glim_MapGrid2f]
}

NAKED glMaterialf() {
	__asm jmp [__glim_Materialf]
}

NAKED glMaterialfv() {
	__asm jmp [__glim_Materialfv]
}

NAKED glMateriali() {
	__asm jmp [__glim_Materiali]
}

NAKED glMaterialiv() {
	__asm jmp [__glim_Materialiv]
}

NAKED glMatrixMode() {
	__asm jmp [__glim_MatrixMode]
}

NAKED glMultMatrixd() {
	__asm jmp [__glim_MultMatrixd]
}

NAKED glMultMatrixf() {
	__asm jmp [__glim_MultMatrixf]
}

NAKED glNewList() {
	__asm jmp [__glim_NewList]
}

NAKED glNormal3b() {
	__asm jmp [__glim_Normal3b]
}

NAKED glNormal3bv() {
	__asm jmp [__glim_Normal3bv]
}

NAKED glNormal3d() {
	__asm jmp [__glim_Normal3d]
}

NAKED glNormal3dv() {
	__asm jmp [__glim_Normal3dv]
}

NAKED glNormal3f() {
	__asm jmp [__glim_Normal3f]
}

NAKED glNormal3fv() {
	__asm jmp [__glim_Normal3fv]
}

NAKED glNormal3i() {
	__asm jmp [__glim_Normal3i]
}

NAKED glNormal3iv() {
	__asm jmp [__glim_Normal3iv]
}

NAKED glNormal3s() {
	__asm jmp [__glim_Normal3s]
}

NAKED glNormal3sv() {
	__asm jmp [__glim_Normal3sv]
}

NAKED glNormalPointer() {
	__asm jmp [__glim_NormalPointer]
}

NAKED glOrtho() {
	__asm jmp [__glim_Ortho]
}

NAKED glPassThrough() {
	__asm jmp [__glim_PassThrough]
}

NAKED glPixelMapfv() {
	__asm jmp [__glim_PixelMapfv]
}

NAKED glPixelMapuiv() {
	__asm jmp [__glim_PixelMapuiv]
}

NAKED glPixelMapusv() {
	__asm jmp [__glim_PixelMapusv]
}

NAKED glPixelStoref() {
	__asm jmp [__glim_PixelStoref]
}

NAKED glPixelStorei() {
	__asm jmp [__glim_PixelStorei]
}

NAKED glPixelTransferf() {
	__asm jmp [__glim_PixelTransferf]
}

NAKED glPixelTransferi() {
	__asm jmp [__glim_PixelTransferi]
}

NAKED glPixelZoom() {
	__asm jmp [__glim_PixelZoom]
}

NAKED glPointSize() {
	__asm jmp [__glim_PointSize]
}

NAKED glPolygonMode() {
	__asm jmp [__glim_PolygonMode]
}

NAKED glPolygonOffset() {
	__asm jmp [__glim_PolygonOffset]
}

NAKED glPolygonStipple() {
	__asm jmp [__glim_PolygonStipple]
}

NAKED glPopAttrib() {
	__asm jmp [__glim_PopAttrib]
}

NAKED glPopClientAttrib() {
	__asm jmp [__glim_PopClientAttrib]
}

NAKED glPopMatrix() {
	__asm jmp [__glim_PopMatrix]
}

NAKED glPopName() {
	__asm jmp [__glim_PopName]
}

NAKED glPrioritizeTextures() {
	__asm jmp [__glim_PrioritizeTextures]
}

NAKED glPushAttrib() {
	__asm jmp [__glim_PushAttrib]
}

NAKED glPushClientAttrib() {
	__asm jmp [__glim_PushClientAttrib]
}

NAKED glPushMatrix() {
	__asm jmp [__glim_PushMatrix]
}

NAKED glPushName() {
	__asm jmp [__glim_PushName]
}

NAKED glRasterPos2d() {
	__asm jmp [__glim_RasterPos2d]
}

NAKED glRasterPos2dv() {
	__asm jmp [__glim_RasterPos2dv]
}

NAKED glRasterPos2f() {
	__asm jmp [__glim_RasterPos2f]
}

NAKED glRasterPos2fv() {
	__asm jmp [__glim_RasterPos2fv]
}

NAKED glRasterPos2i() {
	__asm jmp [__glim_RasterPos2i]
}

NAKED glRasterPos2iv() {
	__asm jmp [__glim_RasterPos2iv]
}

NAKED glRasterPos2s() {
	__asm jmp [__glim_RasterPos2s]
}

NAKED glRasterPos2sv() {
	__asm jmp [__glim_RasterPos2sv]
}

NAKED glRasterPos3d() {
	__asm jmp [__glim_RasterPos3d]
}

NAKED glRasterPos3dv() {
	__asm jmp [__glim_RasterPos3dv]
}

NAKED glRasterPos3f() {
	__asm jmp [__glim_RasterPos3f]
}

NAKED glRasterPos3fv() {
	__asm jmp [__glim_RasterPos3fv]
}

NAKED glRasterPos3i() {
	__asm jmp [__glim_RasterPos3i]
}

NAKED glRasterPos3iv() {
	__asm jmp [__glim_RasterPos3iv]
}

NAKED glRasterPos3s() {
	__asm jmp [__glim_RasterPos3s]
}

NAKED glRasterPos3sv() {
	__asm jmp [__glim_RasterPos3sv]
}

NAKED glRasterPos4d() {
	__asm jmp [__glim_RasterPos4d]
}

NAKED glRasterPos4dv() {
	__asm jmp [__glim_RasterPos4dv]
}

NAKED glRasterPos4f() {
	__asm jmp [__glim_RasterPos4f]
}

NAKED glRasterPos4fv() {
	__asm jmp [__glim_RasterPos4fv]
}

NAKED glRasterPos4i() {
	__asm jmp [__glim_RasterPos4i]
}

NAKED glRasterPos4iv() {
	__asm jmp [__glim_RasterPos4iv]
}

NAKED glRasterPos4s() {
	__asm jmp [__glim_RasterPos4s]
}

NAKED glRasterPos4sv() {
	__asm jmp [__glim_RasterPos4sv]
}

NAKED glReadBuffer() {
	__asm jmp [__glim_ReadBuffer]
}

NAKED glReadPixels() {
	__asm jmp [__glim_ReadPixels]
}

NAKED glRectd() {
	__asm jmp [__glim_Rectd]
}

NAKED glRectdv() {
	__asm jmp [__glim_Rectdv]
}

NAKED glRectf() {
	__asm jmp [__glim_Rectf]
}

NAKED glRectfv() {
	__asm jmp [__glim_Rectfv]
}

NAKED glRecti() {
	__asm jmp [__glim_Recti]
}

NAKED glRectiv() {
	__asm jmp [__glim_Rectiv]
}

NAKED glRects() {
	__asm jmp [__glim_Rects]
}

NAKED glRectsv() {
	__asm jmp [__glim_Rectsv]
}

NAKED glRenderMode() {
	__asm jmp [__glim_RenderMode]
}

NAKED glRotated() {
	__asm jmp [__glim_Rotated]
}

NAKED glRotatef() {
	__asm jmp [__glim_Rotatef]
}

NAKED glScaled() {
	__asm jmp [__glim_Scaled]
}

NAKED glScalef() {
	__asm jmp [__glim_Scalef]
}

NAKED glScissor() {
	__asm jmp [__glim_Scissor]
}

NAKED glSelectBuffer() {
	__asm jmp [__glim_SelectBuffer]
}

NAKED glShadeModel() {
	__asm jmp [__glim_ShadeModel]
}

NAKED glStencilFunc() {
	__asm jmp [__glim_StencilFunc]
}

NAKED glStencilMask() {
	__asm jmp [__glim_StencilMask]
}

NAKED glStencilOp() {
	__asm jmp [__glim_StencilOp]
}

NAKED glTexCoord1d() {
	__asm jmp [__glim_TexCoord1d]
}

NAKED glTexCoord1dv() {
	__asm jmp [__glim_TexCoord1dv]
}

NAKED glTexCoord1f() {
	__asm jmp [__glim_TexCoord1f]
}

NAKED glTexCoord1fv() {
	__asm jmp [__glim_TexCoord1fv]
}

NAKED glTexCoord1i() {
	__asm jmp [__glim_TexCoord1i]
}

NAKED glTexCoord1iv() {
	__asm jmp [__glim_TexCoord1iv]
}

NAKED glTexCoord1s() {
	__asm jmp [__glim_TexCoord1s]
}

NAKED glTexCoord1sv() {
	__asm jmp [__glim_TexCoord1sv]
}

NAKED glTexCoord2d() {
	__asm jmp [__glim_TexCoord2d]
}

NAKED glTexCoord2dv() {
	__asm jmp [__glim_TexCoord2dv]
}

NAKED glTexCoord2f() {
	__asm jmp [__glim_TexCoord2f]
}

NAKED glTexCoord2fv() {
	__asm jmp [__glim_TexCoord2fv]
}

NAKED glTexCoord2i() {
	__asm jmp [__glim_TexCoord2i]
}

NAKED glTexCoord2iv() {
	__asm jmp [__glim_TexCoord2iv]
}

NAKED glTexCoord2s() {
	__asm jmp [__glim_TexCoord2s]
}

NAKED glTexCoord2sv() {
	__asm jmp [__glim_TexCoord2sv]
}

NAKED glTexCoord3d() {
	__asm jmp [__glim_TexCoord3d]
}

NAKED glTexCoord3dv() {
	__asm jmp [__glim_TexCoord3dv]
}

NAKED glTexCoord3f() {
	__asm jmp [__glim_TexCoord3f]
}

NAKED glTexCoord3fv() {
	__asm jmp [__glim_TexCoord3fv]
}

NAKED glTexCoord3i() {
	__asm jmp [__glim_TexCoord3i]
}

NAKED glTexCoord3iv() {
	__asm jmp [__glim_TexCoord3iv]
}

NAKED glTexCoord3s() {
	__asm jmp [__glim_TexCoord3s]
}

NAKED glTexCoord3sv() {
	__asm jmp [__glim_TexCoord3sv]
}

NAKED glTexCoord4d() {
	__asm jmp [__glim_TexCoord4d]
}

NAKED glTexCoord4dv() {
	__asm jmp [__glim_TexCoord4dv]
}

NAKED glTexCoord4f() {
	__asm jmp [__glim_TexCoord4f]
}

NAKED glTexCoord4fv() {
	__asm jmp [__glim_TexCoord4fv]
}

NAKED glTexCoord4i() {
	__asm jmp [__glim_TexCoord4i]
}

NAKED glTexCoord4iv() {
	__asm jmp [__glim_TexCoord4iv]
}

NAKED glTexCoord4s() {
	__asm jmp [__glim_TexCoord4s]
}

NAKED glTexCoord4sv() {
	__asm jmp [__glim_TexCoord4sv]
}

NAKED glTexCoordPointer() {
	__asm jmp [__glim_TexCoordPointer]
}

NAKED glTexEnvf() {
	__asm jmp [__glim_TexEnvf]
}

NAKED glTexEnvfv() {
	__asm jmp [__glim_TexEnvfv]
}

NAKED glTexEnvi() {
	__asm jmp [__glim_TexEnvi]
}

NAKED glTexEnviv() {
	__asm jmp [__glim_TexEnviv]
}

NAKED glTexGend() {
	__asm jmp [__glim_TexGend]
}

NAKED glTexGendv() {
	__asm jmp [__glim_TexGendv]
}

NAKED glTexGenf() {
	__asm jmp [__glim_TexGenf]
}

NAKED glTexGenfv() {
	__asm jmp [__glim_TexGenfv]
}

NAKED glTexGeni() {
	__asm jmp [__glim_TexGeni]
}

NAKED glTexGeniv() {
	__asm jmp [__glim_TexGeniv]
}

NAKED glTexImage1D() {
	__asm jmp [__glim_TexImage1D]
}

NAKED glTexImage2D() {
	__asm jmp [__glim_TexImage2D]
}

NAKED glTexParameterf() {
	__asm jmp [__glim_TexParameterf]
}

NAKED glTexParameterfv() {
	__asm jmp [__glim_TexParameterfv]
}

NAKED glTexParameteri() {
	__asm jmp [__glim_TexParameteri]
}

NAKED glTexParameteriv() {
	__asm jmp [__glim_TexParameteriv]
}

NAKED glTexSubImage1D() {
	__asm jmp [__glim_TexSubImage1D]
}

NAKED glTexSubImage2D() {
	__asm jmp [__glim_TexSubImage2D]
}

NAKED glTranslated() {
	__asm jmp [__glim_Translated]
}

NAKED glTranslatef() {
	__asm jmp [__glim_Translatef]
}

NAKED glVertex2d() {
	__asm jmp [__glim_Vertex2d]
}

NAKED glVertex2dv() {
	__asm jmp [__glim_Vertex2dv]
}

NAKED glVertex2f() {
	__asm jmp [__glim_Vertex2f]
}

NAKED glVertex2fv() {
	__asm jmp [__glim_Vertex2fv]
}

NAKED glVertex2i() {
	__asm jmp [__glim_Vertex2i]
}

NAKED glVertex2iv() {
	__asm jmp [__glim_Vertex2iv]
}

NAKED glVertex2s() {
	__asm jmp [__glim_Vertex2s]
}

NAKED glVertex2sv() {
	__asm jmp [__glim_Vertex2sv]
}

NAKED glVertex3d() {
	__asm jmp [__glim_Vertex3d]
}

NAKED glVertex3dv() {
	__asm jmp [__glim_Vertex3dv]
}

NAKED glVertex3f() {
	__asm jmp [__glim_Vertex3f]
}

NAKED glVertex3fv() {
	__asm jmp [__glim_Vertex3fv]
}

NAKED glVertex3i() {
	__asm jmp [__glim_Vertex3i]
}

NAKED glVertex3iv() {
	__asm jmp [__glim_Vertex3iv]
}

NAKED glVertex3s() {
	__asm jmp [__glim_Vertex3s]
}

NAKED glVertex3sv() {
	__asm jmp [__glim_Vertex3sv]
}

NAKED glVertex4d() {
	__asm jmp [__glim_Vertex4d]
}

NAKED glVertex4dv() {
	__asm jmp [__glim_Vertex4dv]
}

NAKED glVertex4f() {
	__asm jmp [__glim_Vertex4f]
}

NAKED glVertex4fv() {
	__asm jmp [__glim_Vertex4fv]
}

NAKED glVertex4i() {
	__asm jmp [__glim_Vertex4i]
}

NAKED glVertex4iv() {
	__asm jmp [__glim_Vertex4iv]
}

NAKED glVertex4s() {
	__asm jmp [__glim_Vertex4s]
}

NAKED glVertex4sv() {
	__asm jmp [__glim_Vertex4sv]
}

NAKED glVertexPointer() {
	__asm jmp [__glim_VertexPointer]
}

NAKED glViewport() {
	__asm jmp [__glim_Viewport]
}


#ifdef __cplusplus
}
#endif

