
/* Generated by funcptrs_h.pl */
#ifndef FUNCPTRS_H
#define FUNCPTRS_H

#ifdef EXTERN_GLIM
#undef EXTERN_GLIM
#endif

#ifdef ASSIGNMENT
#undef ASSIGNMENT
#endif

#ifdef WIN32
#define FUNCAPI __stdcall
#else
#define FUNCAPI
#endif

typedef void (FUNCAPI *GLapifunc)(); 

#ifdef DEFINE_FUNCPTRS
#define EXTERN_GLIM
#define ASSIGNMENT = (GLapifunc) 4
#else
#define EXTERN_GLIM extern
#define ASSIGNMENT
#endif


#ifdef __cplusplus
extern "C" {
#endif

EXTERN_GLIM void (FUNCAPI *__glim_Accum)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_AlphaFunc)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_AreTexturesResident)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_ArrayElement)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Begin)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_BindTexture)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Bitmap)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_BlendFunc)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_CallList)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_CallLists)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Clear)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_ClearAccum)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_ClearColor)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_ClearDepth)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_ClearIndex)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_ClearStencil)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_ClipPlane)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color3b)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color3bv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color3d)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color3dv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color3f)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color3fv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color3i)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color3iv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color3s)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color3sv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color3ub)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color3ubv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color3ui)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color3uiv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color3us)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color3usv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color4b)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color4bv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color4d)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color4dv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color4f)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color4fv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color4i)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color4iv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color4s)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color4sv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color4ub)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color4ubv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color4ui)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color4uiv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color4us)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Color4usv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_ColorMask)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_ColorMaterial)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_ColorPointer)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_CopyPixels)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_CopyTexImage1D)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_CopyTexImage2D)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_CopyTexSubImage1D)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_CopyTexSubImage2D)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_CullFace)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_DeleteLists)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_DeleteTextures)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_DepthFunc)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_DepthMask)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_DepthRange)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Disable)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_DisableClientState)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_DrawArrays)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_DrawBuffer)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_DrawElements)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_DrawPixels)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_EdgeFlag)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_EdgeFlagPointer)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_EdgeFlagv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Enable)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_EnableClientState)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_End)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_EndList)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_EvalCoord1d)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_EvalCoord1dv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_EvalCoord1f)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_EvalCoord1fv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_EvalCoord2d)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_EvalCoord2dv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_EvalCoord2f)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_EvalCoord2fv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_EvalMesh1)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_EvalMesh2)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_EvalPoint1)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_EvalPoint2)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_FeedbackBuffer)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Finish)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Flush)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Fogf)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Fogfv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Fogi)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Fogiv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_FrontFace)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Frustum)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GenLists)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GenTextures)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetBooleanv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetClipPlane)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetDoublev)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetError)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetFloatv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetIntegerv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetLightfv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetLightiv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetMapdv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetMapfv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetMapiv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetMaterialfv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetMaterialiv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetPixelMapfv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetPixelMapuiv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetPixelMapusv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetPointerv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetPolygonStipple )() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetString)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetTexEnvfv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetTexEnviv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetTexGendv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetTexGenfv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetTexGeniv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetTexImage)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetTexLevelParameterfv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetTexLevelParameteriv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetTexParameterfv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_GetTexParameteriv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Hint)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_IndexMask)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_IndexPointer)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Indexd)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Indexdv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Indexf)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Indexfv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Indexi)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Indexiv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Indexs)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Indexsv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Indexub)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Indexubv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_InitNames)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_InterleavedArrays)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_IsEnabled)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_IsList)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_IsTexture)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_LightModelf)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_LightModelfv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_LightModeli)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_LightModeliv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Lightf)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Lightfv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Lighti)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Lightiv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_LineStipple)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_LineWidth)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_ListBase)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_LoadIdentity)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_LoadMatrixd)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_LoadMatrixf)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_LoadName)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_LogicOp)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Map1d)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Map1f)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Map2d)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Map2f)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_MapGrid1d)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_MapGrid1f)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_MapGrid2d)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_MapGrid2f)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Materialf)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Materialfv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Materiali)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Materialiv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_MatrixMode)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_MultMatrixd)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_MultMatrixf)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_NewList)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Normal3b)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Normal3bv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Normal3d)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Normal3dv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Normal3f)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Normal3fv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Normal3i)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Normal3iv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Normal3s)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Normal3sv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_NormalPointer)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Ortho)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PassThrough)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PixelMapfv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PixelMapuiv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PixelMapusv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PixelStoref)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PixelStorei)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PixelTransferf)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PixelTransferi)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PixelZoom)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PointSize)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PolygonMode)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PolygonOffset)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PolygonStipple)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PopAttrib)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PopClientAttrib)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PopMatrix)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PopName)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PrioritizeTextures)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PushAttrib)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PushClientAttrib)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PushMatrix)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_PushName)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos2d)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos2dv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos2f)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos2fv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos2i)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos2iv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos2s)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos2sv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos3d)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos3dv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos3f)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos3fv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos3i)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos3iv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos3s)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos3sv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos4d)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos4dv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos4f)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos4fv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos4i)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos4iv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos4s)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RasterPos4sv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_ReadBuffer)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_ReadPixels)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Rectd)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Rectdv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Rectf)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Rectfv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Recti)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Rectiv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Rects)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Rectsv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_RenderMode)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Rotated)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Rotatef)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Scaled)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Scalef)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Scissor)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_SelectBuffer)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_ShadeModel)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_StencilFunc)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_StencilMask)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_StencilOp)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord1d)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord1dv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord1f)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord1fv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord1i)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord1iv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord1s)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord1sv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord2d)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord2dv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord2f)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord2fv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord2i)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord2iv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord2s)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord2sv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord3d)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord3dv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord3f)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord3fv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord3i)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord3iv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord3s)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord3sv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord4d)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord4dv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord4f)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord4fv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord4i)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord4iv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord4s)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoord4sv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexCoordPointer)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexEnvf)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexEnvfv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexEnvi)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexEnviv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexGend)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexGendv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexGenf)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexGenfv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexGeni)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexGeniv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexImage1D)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexImage2D)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexParameterf)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexParameterfv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexParameteri)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexParameteriv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexSubImage1D)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_TexSubImage2D)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Translated)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Translatef)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex2d)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex2dv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex2f)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex2fv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex2i)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex2iv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex2s)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex2sv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex3d)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex3dv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex3f)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex3fv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex3i)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex3iv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex3s)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex3sv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex4d)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex4dv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex4f)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex4fv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex4i)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex4iv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex4s)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Vertex4sv)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_VertexPointer)() ASSIGNMENT;
EXTERN_GLIM void (FUNCAPI *__glim_Viewport)() ASSIGNMENT;

#ifdef __cplusplus
}
#endif

#endif
