
print << 'EOF';

/* Generated by funcapi.pl */

#include <stdlib.h>
#include <stdio.h>

#include "glcontext/glcontext.h"
#include "gllocal.h"

#define DEFINE_FUNCPTRS
#include "funcptrs.h"

void
__gllocal_InitFuncPtrs(void) {

EOF

open(FILE, "localfuncs.txt");

@localfuncs = {};
$i = 0;

while ($line = <FILE>) {
	chomp $line;
	if ($line ne "") {
		push (@localfuncs,$line);
		$i++;
	}
}


do {
  $func = <STDIN>;
  chomp $func;

  if ($func =~ /(.*) (.*)/) {
    $func = $1;
    if ($func ne "") {
	  $pre = "glstate";

	  foreach $elem (@localfuncs) {
		$pre = "gllocal" if ($elem eq $func);
	  }

	  print "\t__glim_$func = (GLapifunc)  __${pre}_${func};\n";
    }
  }
} until eof();

print << 'EOF'
};

#ifdef __cplusplus
}
#endif


EOF
