
print << 'EOF';

/* Generated by funcptrs_h.pl */
#ifndef FUNCPTRS_H
#define FUNCPTRS_H

#ifdef EXTERN_GLIM
#undef EXTERN_GLIM
#endif

#ifdef ASSIGNMENT
#undef ASSIGNMENT
#endif

#ifdef WIN32
#define FUNCAPI __stdcall
#else
#define FUNCAPI
#endif

typedef void (FUNCAPI *GLapifunc)(); 

#ifdef DEFINE_FUNCPTRS
#define EXTERN_GLIM
#define ASSIGNMENT = (GLapifunc) 4
#else
#define EXTERN_GLIM extern
#define ASSIGNMENT
#endif


#ifdef __cplusplus
extern "C" {
#endif

EOF

do {
  $_ = <STDIN>;
  chomp;

  if ($_ =~ /(.*) (.*)/) {
    print "EXTERN_GLIM void (FUNCAPI *__glim_$1)() ASSIGNMENT;\n";
  }
} until eof();

print << 'EOF'

#ifdef __cplusplus
}
#endif

#endif
EOF
